install_data(
  'io.github.tejaskhanna989.KastManager.desktop',
  install_dir: join_paths(get_option('datadir'), 'applications'),
)

install_data(
  'io.github.tejaskhanna989.KastManager.metainfo.xml',
  install_dir: join_paths(get_option('datadir'), 'metainfo'),
)

install_subdir(
  join_paths('icons', 'public', 'hicolor'),
  install_dir: join_paths(datadir, 'icons'),
)
